### PR TITLE
Thomas cleanup: Few cleanup tasks from Thomas the Train Engine PR

### PR DESCRIPTION
**Pull request by Shadowfiend**
Direct import from #87 .

### CODE REVIEW

**Review by ironng — COMMENTED** [review]
Looks great so far 💅 

I tried testing this out locally but was hit with a compilation error that prevents the dapp from loading:
```
../tbtc.js/src/lib/backoff.js 66:15
Module parse failed: Cannot use keyword 'await' outside an async function (66:15)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       try {
|         console.debug(`making attempt number ${attempt}`);
>         return await fn();
|       } catch (error) {
|         if (!errorMatcher(error)) {
```
(I realize this is from the previous PR. Sorry I didn't test it then! 🙈 )

We should be good if return the `await fn()` inside an anonymous async function. Seems like Node doesn't support [top level await until v14.3](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#support-for-top-level-await).

**Comment by Shadowfiend** [comment]
🤔 but this transpiled fine in dev and is running on Ropsten now 🤨🙃

**Comment by Shadowfiend** [comment]
Also this already is inside an anonymous async function (the one returned by `backoffRetrier`. I now remember seeing this issue briefly when I first wrote the code, trying to remember how it got fixed... Feels like it might have been a transpiler issue. I'll poke it some more tomorrow.

**Comment by ironng** [comment]
😕 🙃 🤔  Maybe I need to blow away node modules? I'll retry.

**Comment by ironng** [comment]
I did fresh installs after deleting node modules for both tbtc.js and the dapp and still encountered the compiler error. FWIW I'm running Node v11.15, but like you mentioned, it seems like a transpiler thing.

**Comment by Shadowfiend** [comment]
😭😭😭

**Comment by Shadowfiend** [comment]
Fixed the tranpsilation issue.

**Review by ironng — APPROVED** [review]
🚀

**Pull request merged**
