### PR TITLE
Updated web3 dependencies versions

### PR DESCRIPTION
**Pull request by nkuba**
Updated web3 and web3-provider-engine to the latest versions.

### CODE REVIEW

**Comment by beaushinkle** [comment]
Can you include in the PR title and commit description that the new version of web3 is `1.3.6`? I've found this helps me in the past when I'm looking through github PRs

**Comment by beaushinkle** [comment]
I'm getting:
```
~/local/tbtc.js web3-update
❯ npm i             
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/bfilter/loady@git+https:/github.com/chjj/loady.git#b94958b7ee061518f4b85ea6da380e7ee93222d5" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beaushinkle/.npm/_logs/2021-05-26T14_14_30_168Z-debug.log
```
locally

**Comment by beaushinkle** [comment]
I was able to get installation working by removing `package-lock.json`, but I do think that there's something funky going on

**Comment by nkuba** [comment]
> I was able to get the installation working by removing `package-lock.json`, but I do think that there's something funky going on
> 
> edit: I think the funkiness is on my side. I was able to run `npm ci` fine

It's not only your problem. I also noticed that `npm install` fails and `npm ci` works on my machine. I manually updated `package-lock.json` in commit bb80aa82dd8efe92da5f63b81a2bc6e01b4820c7, with this change `npm install` works fine 😕

**Comment by beaushinkle** [comment]
Confirmed that `npm i` runs fine now!

**Pull request merged**
