### PR TITLE
In `purchaseSignerBondsAtAuction` get rightful ETH by calling `withdrawFunds`

### PR DESCRIPTION
**Pull request by daramir**
# Description
- sendSafely action on the `withdrawFunds` method: 
    This way the purchaser will also get the sanctioned ETH as part of `purchaseSignerBondsAtAuction`

## Checklist
- [X] Fork keep-network/tbtc.js
- [X] Clone your fork
- [X] Describe the change you are intending to undertake in the PR description.

Before marking the PR as ready for review, make sure:
- [X] It passes the linter checks.
- [ ] Your changes have sufficient test coverage (e.g regression tests have been added for bug fixes, unit tests for new features)
tests disabled at the moment
- [X] Commits must be signed.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
So I've been background-thinking about this a bit.

I think the methods named exactly the same as contract methods should probably only invoke those contract methods. Instead of making `purchaseSignerBondsAtAuction` call `withdrawFunds`, what do you think about introducing a separate method, something like `takeAuction` or `closeAuction`, that does both?

We should probably also introduce a wrapper for `withdrawFunds`, similar to the one for `purchaseSignerBondsAtAuction`, that just does a `sendSafely`.

**Comment by daramir** [comment]
That makes sense, @Shadowfiend! Will combine both of your advice and update this PR.

**Comment by daramir** [comment]
@Shadowfiend  PR updated!

**Review by Shadowfiend — APPROVED** [review]
Yes yes, let us do it!

**Comment by Shadowfiend** [comment]
Sorry for the wait here <_<

**Comment by Shadowfiend** [comment]
Actually it probably also makes sense to add an `approve` step before `purchaseSignerBondsAtAuction` here, to approve the deposit to spend the sender's BTC.

**Comment by daramir** [comment]
That should be coved by the `purchaseSignerBondsAtAuction` function itself at the moment. I'm happy to create another PR to extract the approve logic from it to `approveTbtcForDeposit`, or just plain `approve`. Is that what you're after @Shadowfiend ?  😁

**Comment by Shadowfiend** [comment]
Oh actually no, I just forgot it was already happening in there 😬

**Comment by daramir** [comment]
Cool, all done then! 🎉

**Pull request merged**
